### ISSUE TITLE
! Package biblatex Error: Style 'abnt' not found.

### ISSUE THREAD

**Issue by Isaac25silva** [OpenFEI/Classe-Latex-FEI#11]
Estou com esse erro no texmaker quando uso a classe.
_! Package biblatex Error: Style 'abnt' not found._

E tenho esse erro quando uso o makefile
_bash: biber: command not found
make: **\* [templates] Error 127_

**Comment by RodrigoPrior** [comment]
se vc baixou o ultimo release, tenta da checkout na versao 2.0:

    $ git pull
    $ git checkout 2.0

eh a versao antes da mudanca radical da classe  :wink:

**Comment by douglasrizzo** [comment]
Esse aí é um problema da nova versão, que acontece se tu baixar a classe do master ou testing do GitHub.

Você pode usar a versão estável que está no CTAN, baixando direto pelo [site](http://ctan.org/pkg/fei) ou pelo [TeX Live Manager](https://www.tug.org/texlive/tlmgr.html) (se estiver instalado), ou então baixar o release 2.0.1 [aqui](https://github.com/OpenFEI/Classe-Latex-FEI/tag/2.0.1).

Se você quiser ter um goixtinho da nova versão, baixa ela [aqui](https://github.com/douglasrizzo/Classe-Latex-FEI), mas como mudou a forma de gerar a bibliografia por causa do fim de suporte ao pacote de referências da abnTeX que a gente usava, é melhor ler o manual. Tem uma seção que explica as diferenças.
