### ISSUE TITLE
build e testes

### ISSUE THREAD

**Issue by RodrigoPrior** [OpenFEI/Classe-Latex-FEI#3]
Vale a pena desenvolver plataforma para build e teste?

build: alguma coisa como fabric, shell, phing, chef, puppet etc
teste: alguma coisa como travis, jenkins etc

ref.:
https://launchpad.net/rubber/
https://gist.github.com/snim2/9160862

**Comment by douglasrizzo** [comment]
Marquei como consertado, mas deu errado. O Travis está compilando a classe agora, usando o Makefile que eu criei.
